// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.Design;
using System.Linq;
using System.Text.Json.Serialization;
using ClientMsgs;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Models.AiResponse;
using Models.Books;
using Models.Notifications;
using ViewGeneratorBase;

namespace Models
{
    public interface IUserService
    {
        //Task<User> AuthenticateSession(int userId, string sessionId, string password);
        Task<Models.User> AuthenticateSession(System.Guid userId, string sessionId, string password);




        Task<User> Authenticate(string phoneNumber, string password);
        Task<SessionMakeResult> MakeSession(User user, Platform modelPlatform);
        Task<int> removeAnothers(Guid userId);


        Task<int> logout(User userId,Guid sessId);
        Task<Models.User> getUser(Guid userId);
        Task<bool> getAcess(Guid conId,Guid usId, Guid usr2Id);
        Task<bool> getAcess(Guid usId, Guid usr2Id);
    }
    public enum UserType{
        Customer=0,
        MockThird=1,
    }
    public class SessionCacheData
    {
        public string pass;
        public DateTime lastSyncFromRedis;
        public DateTime lastUse;
    }
    [BigTable]
    [Display(Name = "دانشجویان")]
    [InsertAccess(AdminUserRole.SUPER_USER)]
    [UpdateAccess(AdminUserRole.SUPER_USER)]
    [SelectAccess(AdminUserRole.SUPER_USER)]
    [ViewAccess(AdminUserRole.SUPER_USER,AdminUserRole.SUPPORT)]
    public class User : BaseUser
    {
        


        public string phoneNumber { get; set; }

        [Display(Name = "سرویس فعال")]
        public int ServiceId { get; set; }

        [Display(Name = "زمان خرید سرویس")]
        //[Column(TypeName = "datetime")]
        public DateTime? ServiceBuyTime { get; set; }

        [Display(Name = "اعتبار سرویس")]
        //[Column(TypeName = "datetime")]
        public DateTime? ServiceValidTime { get; set; }


        public UserType userType { get; set; } = UserType.Customer;

        [ForeignKey(nameof(ServiceId))]
        [InverseProperty(nameof(Service.users))]
        [Display(Name = "سرویس فعال")]
        public  Service service { get; set; }


        public DateTime registerDate { get; set; } = DateTime.MinValue;
        
        [CustomIgnoreTag(CustomIgnoreTag.Kind.CLIENT)]
        public string pass { get; set; }


        public Guid? examinerFinder { get; set; } = null; 

        public string displayName { get; set; }
        public string firstAndLastName { get; set; }


        public bool disableZarinPalBuying { get; set; } = false;
        
        [Display(Name = "دستگاه های فعال")]
        [InverseProperty(nameof(IUserEntity.user))]
        public  ICollection<DeviceSessions> DeviceSessions { get; set; }

        [Display(Name = "اعلانات")]
        [ScaffoldColumn(false)]
        [InverseProperty(nameof(UserInboxItem.Customer))]
        public  ICollection<UserInboxItem> userInboxItems { get; set; }
        


        [ScaffoldColumn(false)]
        [InverseProperty(nameof(TextTools.UserNote.Customer))]
        public  ICollection<TextTools.UserNote> notes { get; set; }
        

        [SelectAccess(AdminUserRole.SUPPORT,AdminUserRole.SUPER_USER)]
        public IQueryable<AResponseAdjust> Revises(IServiceProvider Services)
        {
            var oldDb = Services.GetRequiredService<IAssetManager>();
            return oldDb.getDbSet<AResponseAdjust>().Where(x => x.response.examPartSession.CustomerId == this.id).OrderBy(x => x.createAt);
        }

        [BigTable]
        [SelectAccess(AdminUserRole.SUPPORT,AdminUserRole.SUPER_USER)]
        public class DResPonse:IIdMapper<Guid>
        {
            public Guid id { get; set; }
           


            [ForeignKey(nameof(main))]
            public Guid mainId { get=>id; set=>id=value; }
            
            public AResponseAdjust main { get; set; }
            public string text { get; set; }
            public string examName { get; set; }
            public string sectionTitle { get; set; }
            public string questionName { get; set; }
            public DateTime createAt { get; set; }
            public AdjustingState state { get; set; }
            [ForeignKeyAttr(typeof(Response))]
            public Guid responseId { get; set; }
            public object getId()
            {
                return id;
            }
            [JsonIgnore]
            public ChangeEventList onChanges { get; set; }
        }
        [SelectAccess(AdminUserRole.SUPPORT,AdminUserRole.SUPER_USER)]
        public IQueryable<DResPonse> Revises2(IServiceProvider Services)
        {
            var oldDb = Services.GetRequiredService<IAssetManager>();
            return oldDb.getDbSet<AResponseAdjust>().Where(x => x.response.examPartSession.CustomerId == this.id).Select(x=>new
                DResPonse(){
                    id=x.id,
                    text=x.text,
                    examName=x.response.question.section.exam.Name,
                    sectionTitle=x.response.question.section.Title,
                    questionName=x.response.question.Name,
                    createAt=x.createAt,
                    state=x.state,
                    responseId=x.responseId
            }).OrderByDescending(x => x.createAt);
        }


        [Display(Name = "آموزگاران")]
        [InverseProperty(nameof(UserExaminer.user))]
        [ScaffoldColumn(false)]
        public ICollection<UserExaminer> examiners { get; set; }


        [Display(Name = "دانشجویان")]
        [InverseProperty(nameof(UserExaminer.examiner))]
        [ScaffoldColumn(false)]
        public ICollection<UserExaminer> clients { get; set; }


        [Display(Name = "جعبه لایتنر")]
        [InverseProperty(nameof(UserLeitnerCard.Customer))]
        [ScaffoldColumn(false)]
        public  ICollection<UserLeitnerCard> leitnerBoxs { get; set; }

        
        [Display(Name = "پیشرفت در آزمن ها")]
        [ScaffoldColumn(false)]
        [InverseProperty(nameof(IUserEntity.user))]
        public virtual ICollection<SectionUserProgress> SectionUserProgress { get; set; }

        [Display(Name = "لغت نامه شخصی")]
        [InverseProperty(nameof(IUserEntity.user))]
        [ScaffoldColumn(false)]
        public  ICollection<SelfDictionary> SelfDictionary { get; set; }

        [Display(Name = "سرویس‌های خریده شده")]
        [ScaffoldColumn(false)]
        [InverseProperty(nameof(ServiceBuy.Customer))]
        [SelectAccess(AdminUserRole.SUPPORT)]
        public  ICollection<ServiceBuy> ServiceBuys { get; set; }

        [Display(Name = "تیکت ها")]
        [ScaffoldColumn(false)]
        [InverseProperty(nameof(IUserEntity.user))]
        public  ICollection<Ticketing> Ticketing { get; set; }


        [Display(Name = "بوکمارک ها")]
        [ScaffoldColumn(false)]
        [InverseProperty(nameof(IUserEntity.user))]
        [SelectAccess(AdminUserRole.SUPPORT)]
        public ICollection<UserBookmark> UserBookmarks { get; set; }

        [Display(Name = "اطلاعات تکمیلی")]
        [InverseProperty(nameof(IUserEntity.user))]
        public UserDetail UserDetail { get; set; }

        [Display(Name = "آخرین پیامک ارسال شده")]
        [ScaffoldColumn(false)]
        public DateTime? LastSmsSend { get; internal set; }
        
        public string avatar { get; set; }

        [SelectAccess(AdminUserRole.SUPPORT)]
        [InverseProperty(nameof(ExamPartSession.Customer))]
        public ICollection<ExamPartSession> examPartSessions { get; set; }


        [SelectAccess(AdminUserRole.SUPPORT)]
        [InverseProperty(nameof(ExamSession.Customer))]
        public ICollection<ExamSession> examSessions { get; set; }

        [InverseProperty(nameof(UserSectionData.Customer))]
        public ICollection<UserSectionData> sectionDatas { get; set; }

        [InverseProperty(nameof(UserSubjectData.Customer))]
        public ICollection<UserSubjectData> subjectDatas { get; set; }

        [InverseProperty(nameof(UserExamPartData.Customer))]
        public ICollection<UserExamPartData> examPartDatas { get; set; }



        [Display(Name = "وضعیت کلمات")]
        [SelectAccess(AdminUserRole.SUPPORT)]
        [InverseProperty(nameof(UserLeitnerWord.Customer))]
        public ICollection<UserLeitnerWord> words { get; set; }
        

        [InverseProperty(nameof(Report.Customer))]
        public ICollection<Report> reports { get; set; }

        [InverseProperty(nameof(Models.Interview.Response.Customer))]
        public ICollection<Models.Interview.Response> responses { get; set; }

        [InverseProperty(nameof(Models.Interview.TaskLog.Customer))]
        public ICollection<Models.Interview.TaskLog> taskLogs { get; set; }


        [InverseProperty(nameof(UserLog.Customer))]
        public ICollection<UserLog> userLogs { get; set; }
        
        
        [InverseProperty(nameof(PhysicalExam.admin))]
        public ICollection<PhysicalExam> physicalExams { get; set; }
        
        
        [InverseProperty(nameof(PublicDiscountUse.user))]
        public ICollection<PublicDiscountUse> PublicDiscountUses { get; set; }

        
        public string ?email { get; set; }

        //public string chatId { get; set; }
    }

    [InsertAccess(AdminUserRole.SUPER_USER)]
    [UpdateAccess(AdminUserRole.SUPER_USER)]
    [SelectAccess(AdminUserRole.SUPER_USER)]
    public class PhysicalExam : IdMapper<Guid>
    {

        [ForeignKey(nameof(admin))]
        public Guid adminId { get; set; }
        
        [ForeignKey(nameof(adminId))]
        public User admin { get; set; }

        public bool isActive { get; set; }

        public ICollection<PhysicalExamClientRel> physicalExamClientRels { get; set; }
    }

    [InsertAccess(AdminUserRole.SUPER_USER)]
    [UpdateAccess(AdminUserRole.SUPER_USER)]
    [SelectAccess(AdminUserRole.SUPER_USER)]
    public class PhysicalExamClientRel : IdMapper<Guid>
    {
        [ForeignKey(nameof(user))]
        public Guid userId { get; set; }
        
        [ForeignKey(nameof(userId))]
        public User user { get; set; }
        
        
        [ForeignKey(nameof(PhysicalExam))]
        public Guid PhysicalExamId { get; set; }
        
        [ForeignKey(nameof(PhysicalExamId))]
        public PhysicalExam PhysicalExam { get; set; }
        
        
        [ForeignKey(nameof(exam))]
        public int examId { get; set; }
        
        [ForeignKey(nameof(examId))]
        public Exam exam { get; set; }


    }
    
    public class UserExaminerAcess : IQuery<UserExaminer>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public UserExaminerAcess(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IQueryable<UserExaminer> run(IQueryable<UserExaminer> q) 
        {
            var userId=_httpContextAccessor.HttpContext.getUser2Id();
            return q.Where(x => x.examinerId == userId ||x.userId == userId );
        }
        
    }

    [InsertAccess(AdminUserRole.SUPER_USER)]
    [UpdateAccess(AdminUserRole.SUPER_USER)]
    [SelectAccess(AdminUserRole.SUPER_USER,AdminUserRole.SUPPORT)]
    [FroceFillter<UserExaminerAcess>(CustomIgnoreTag.Kind.CLIENT)]
    public class UserExaminer:IdMapper<Guid>,IRemoveable
    {
        [ForeignKey(nameof(user))]
        public Guid userId { get; set; }

        [ForeignKey(nameof(examiner))]
        public Guid examinerId { get; set; }


        [ForeignKey(nameof(userId))]
        public User user { get; set; }

        [ForeignKey(nameof(examinerId))]
        public User examiner { get; set; }

        public bool accepted { get; set; } = false;
        public bool IsRemoved { get; set; } = false;
    }

    
    

    public class UserMigrateData : IIdMapper<Guid>
    {
        public Guid id { get; set; }

        [JsonIgnore]
        [NotMapped]
        public ChangeEventList onChanges { get => throw new NotImplementedException(); set => throw new NotImplementedException(); }

        public DateTime date { get; set; }
        public string vrsion { get; set; }
        public string enitityName { get; set; }


        [ForeignKey(nameof(user))]
        public Guid userId { get; set; }

        [ForeignKey(nameof(userId))]
        public User user { get; set; }


        public object getId()
        {
            return id;
        }
    }
}