// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Models
{
    public enum DeviceType
    {
        Web = 0,
        Windows = 1,
        Android = 2,
        Apple = 3
    }
}