// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ViewGeneratorBase;


namespace Models
{
    [Display(Name = "دستگاه ها")]
    public partial class DeviceSessions : AEntity,IUserEntity
    {
        public DeviceSessions()
        {
            //SyncQueue = new HashSet<SyncQueue>();
        }


        [Display(Name = "نوع دستگاه")]

        public DeviceType Type { get; set; }

        [Display(Name = "نام دستگاه")]
        [Required]
        public string DeviceName { get; set; }

        [Required]
        [ScaffoldColumn(false)]
        public string Token { get; set; }

        [Display(Name = "دانشجو")]
        public Guid userId{ get; set; }

        [Display(Name = "دانشجو")]
        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User.DeviceSessions))]
        public User user { get; set; }

        
        [Display(Name = "آخرین استفاده")]
        public DateTime? LastLoginTime { get; set; }

        [DefaultValue(typeof(DateTime),"04/04/2023")]
        public DateTime LastUpdateTime { get; set; }
    }
}