// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ClientMsgs;
using EnglishToefl.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using ViewGeneratorBase;


namespace Models
{
    public static class EXTENCTION2
    {

        public static User getUser(this HttpContext a)
        {
            object res = null;
            if (a.Items.TryGetValue("user", out res) && res is User)
                return (User)res;
            return null;

        }
       

    }
    public class AsyncableEntityUserQuery : IQuery2<ICustomerEntity2>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AsyncableEntityUserQuery(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IQueryable<T2> run<T2>(IQueryable<T2> q) where T2 : ICustomerEntity2
        {
            var user2Id=_httpContextAccessor.HttpContext.getUser2Id();
            //var userId=_httpContextAccessor.HttpContext.getUserId();
            
            return q.Where(x => x.CustomerId == user2Id //|| x.CustomerId == userId
            );

           
            
        }
    }
    
    
    public class AsyncableEntityUserQueryUser2 : IQuery2<ICustomerEntity2>
    {
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AsyncableEntityUserQueryUser2(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IQueryable<T2> run<T2>(IQueryable<T2> q) where T2 : ICustomerEntity2
        {
            var user2Id=_httpContextAccessor.HttpContext.getUser2Id();
            
            return q.Where(x => x.CustomerId == user2Id );

           
            
        }
    }


    public class AsyncableEntityUserAction : IAction<AsyncableEntiryUser>
    {
        /*public Microsoft.Extensions.DependencyInjection.ServiceCollection serviceCollection;
        AsyncableEntiryUserAction(Microsoft.Extensions.DependencyInjection.ServiceCollection serviceCollection)
        {
            this.serviceCollection = serviceCollection;
        }*/
        private readonly IHttpContextAccessor _httpContextAccessor;

        public AsyncableEntityUserAction(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public async Task<AsyncableEntiryUser> run(AsyncableEntiryUser entity, IServiceProvider Services)
        {
            var value = _httpContextAccessor.HttpContext.getUserId();
            entity.CustomerId = value;
            return entity;
        }
    }

    [FroceFillter<AsyncableEntityUserQuery>(CustomIgnoreTag.Kind.CLIENT)]
    public interface ICustomerEntity2 
    {
        [ForeignKey(nameof(Customer))]
        public Guid CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        public User Customer { get; set; }

    }

    [FroceFillter<AsyncableEntityUserQuery>(CustomIgnoreTag.Kind.CLIENT)]
    public class AsyncableEntiryUser : ASyncableEntity2, ICustomerEntity2
    {
        [ForeignKey(nameof(Customer))]
        public virtual Guid CustomerId { get; set; }

        [ForeignKey(nameof(CustomerId))]
        public virtual User Customer { get; set; }

    }




    public enum ExamMode
    {
        Exam = 1,
        Practice = 2
    }
    
    public class ExtraMsgItem
    {

    }

    public class RequiredBuyMsg: ExtraMsgItem
    {
        public ForeignKey2<ServiceGroup, int> item { get; set; }
    }
    public class TimeLimitMsg : ExtraMsgItem
    {
        public DateTime willReadyOn { get; set; }
    }
    

    public class ResponeFilter : IQuery<Response>
    {

        private readonly IHttpContextAccessor _httpContextAccessor;

        public ResponeFilter(IHttpContextAccessor httpContextAccessor)
        {
            this._httpContextAccessor = httpContextAccessor;
        }
        public IQueryable<Response> run(IQueryable<Response> q) //where T2 : AsyncableEntiryUser
        {
        
            var user2Id = _httpContextAccessor.HttpContext.getUser2Id();
            return q.Where(x => x.examPartSession.CustomerId == user2Id);
            
        }
    }


    public class ResponeSort : IQuery<Response>
    {

        
        public IQueryable<Response> run(IQueryable<Response> q) //where T2 : AsyncableEntiryUser
        {

            
            return q.OrderBy(x => x.EnterDate);
        }
    }
    public enum DataSource
    {
        None=0,
        FromNewServer = 1,
        MigratedFromOldServer = 2,
        CreateForLastScore = 3,
        CreateInNewServerForOldserverMigration=4
    }


    /*[BigTable]
    [Display(Name = "")]
    [FroceFillter<ResponeFilter>(CustomIgnoreTag.Kind.CLIENT)]
    [FroceAction<AsyncableEntityUserAction>(CustomIgnoreTag.Kind.CLIENT)]
    [SelectAccess(AdminUserRole.SUPPORT)]
    [ViewAccess(AdminUserRole.SUPPORT)]
    [DefultSort<ResponeSort>()]
    public class UserQuestion : ASyncableEntity2 {
        [Display(Name = "زمان پاسخ")]
        [DataType(DataType.DateTime)]
        public DateTime enterDate { get; set; }
        
        public DateTime updatedAt { get; set; } = DateTime.UtcNow;


        [JsonIgnore]
        public int IsCorrect { get; set; }


        [Display(Name = "سوال")]
        public int QuestionId { get; set; }

        [ForeignKey(nameof(QuestionId))]
        [InverseProperty(nameof(Question.response))]
        public Question question { get; set; }
        
        
        
        [Display(Name = "جواب")]
        public int responseId { get; set; }

        [ForeignKey(nameof(responseId))]
        public Question response { get; set; }
    }*/

    [BigTable]
    [Display(Name = "پاسخ")]
    [FroceFillter<ResponeFilter>(CustomIgnoreTag.Kind.CLIENT)]
    [FroceAction<AsyncableEntityUserAction>(CustomIgnoreTag.Kind.CLIENT)]
    [SelectAccess(AdminUserRole.SUPPORT)]
    [ViewAccess(AdminUserRole.SUPPORT)]
    [DefultSort<ResponeSort>()]
    public abstract class Response : ASyncableEntity2,IRemoveable
    {
        public Response()
        {
            SyncTime = DateTime.UtcNow;
            updatedAt = DateTime.UtcNow;
        }


        
        public DataSource dataSource { get; set; } = DataSource.FromNewServer;
        public Guid ?cloneFromId { get; set; } = null;

        [Display(Name = "متن")]
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }





        [Display(Name = "زمان پاسخ")]
        [DataType(DataType.DateTime)]
        public DateTime EnterDate { get; set; }


        [Display(Name = "نمره")]
        public decimal? Score { get; set; }
        //[Column(TypeName = "datetime")]

        [Display(Name = "زمان نمره دهی")]
        [DataType(DataType.DateTime)]
        public DateTime ScoredDateTime { get; set; }

        [Display(Name = "زمان سینک")]
        public DateTime SyncTime { get; set; } = DateTime.UtcNow;

        
        public DateTime updatedAt { get; set; } = DateTime.UtcNow;


        public bool IsRemoved { get; set; } = false;


        [JsonIgnore]
        public int IsCorrect { get; set; }

      

        [Display(Name = "مصحح")]
        public Guid? ExaminerId { get; set; }

        [ForeignKey(nameof(ExaminerId))]
        public ApplicationUser Examiner { get; set; }


        [Display(Name = "سوال")]
        public int QuestionId { get; set; }

        [ForeignKey(nameof(QuestionId))]
        [InverseProperty(nameof(Question.response))]
        public virtual Question question { get; set; }


        [ForeignKey(nameof(examPartSession))]
        public Guid examPartSessionId { get; set; }

        [ForeignKey(nameof(examPartSessionId))]
        [InverseProperty(nameof(ExamPartSession.responses))]
        public ExamPartSession examPartSession { get; set; }

        [InverseProperty(nameof(Models.AResponseAdjust.response))]
        public ICollection<AResponseAdjust> adjusts { get; set; }


        public virtual string clacl()
        {

            return Content;

        }


        internal static decimal calcScore(List<int> optionsId, List<int> responseSelectedIds, decimal mark = 1, bool byOrder = false, bool OneWongZero = false)
        {
            if (responseSelectedIds.Count < 1)
                return 0;
            foreach (var option in optionsId.ToList())
            {
                if (!responseSelectedIds.Contains(option))
                {
                    if (OneWongZero)
                        return 0;
                    optionsId.Remove(option);
                    mark--;
                    if (mark > 0)
                        continue;
                    return mark;
                }
            }
            if (optionsId.Count < 1)
                return 0;
            if (byOrder)
            {

                int index = -1;
                foreach (var option in optionsId)
                {
                    int rIndex = responseSelectedIds.IndexOf(option);
                    if (rIndex < index)
                        mark--;
                    index = rIndex;
                }
            }
            if (mark > 0)
                return mark;
            return 0;

        }


        public virtual void refresh() { }

    }

    public class QuestionTrueFalseOptionResponse : Response
    {
        [Column(TypeName = "int[]")]
        public List<ForeignKey2<QuestionOptions, int>> answer { get; set; }


        public override string clacl()
        {
            var questionOptions = (question as QuestionTrueFalseOption).questionOptions.ToList();
                var optionTitles = questionOptions.Where(x=> x.IsCorrect);
                
            var Answer = "";
            if (answer != null && answer.Count() > 0)
                if (answer.Count() > 1)
                    Answer=answer.Select(x => questionOptions.Find(y => y.id == x.Value)?.title.ToString()??"-").Aggregate((l, r) => $"{l},{r}");
                else
                    Answer = questionOptions.Find(y => y.id == answer[0].Value)?.title.ToString()??"-";//TODO tu bazi jabah ye gozine az sole dige entkhab shode exception mide
            this.Content = Answer;
            return Answer;
        }
        public override void refresh()
        {
            if (answer.Count < 1)
            {
                this.Score = 0;
                
                return;
            }
            var fr = answer.Select(x => x.Value).ToList();
            var trr = (question as QuestionTrueFalseOption).questionOptions.Where(x => x.IsCorrect).Select(x => x.id).ToList();
            var intersect = fr.Intersect(trr).ToList();
            if (question.isOr0 && intersect.Count != fr.Count)
            {
                this.Score = 0;
                return;
            }
            //if (intersect.Count != fr.Count)
            //{
              this.Score=question.Mark-(trr.Count-intersect.Count);
            //}
            //this.Score = question.Mark;
            if (this.Score < 0)
                this.Score = 0;
        }
        public  void refresh0() {
            this.Score =calcScore((question as QuestionTrueFalseOption).questionOptions.Where(x => x.IsCorrect).Select(x => x.id).ToList(), answer.Select(x=> x.Value).ToList(), byOrder: false, OneWongZero: question.isOr0);
        }
    }

    public class SingleOptionResponse : QuestionTrueFalseOptionResponse
    {
        public override void refresh()
        {
            if (answer.Count < 1) {
                this.Score = 0;
                return;
            }
            var fr = answer[0].Value;
            var trr = (question as QuestionTrueFalseOption).questionOptions.Find(x => x.id == fr);
            if (trr != null)
            {
                this.Score = trr.IsCorrect ? question.Mark : 0;
            }
            else
                this.Score = 0;
        }
    }

    public class QuestionOptinalResponse : Response
    {

        
        [Display(Name = "ستونها")]
        [Required]
        public List<int> columnsIndex { get; set; }

        public override void refresh()
        {
            if (columnsIndex.Count < 1)
            {
                this.Score = 0;
                return;
            }
            this.Score = question.Mark;
            var trr = (question as QuestionOptinal).questionOptions;
            for (int i = 0; i < trr.Count; ++i)
                if (trr[i].correctColomn != columnsIndex[i])
                {
                    this.Score--;
                }
            if (this.Score < 0)
                this.Score = 0;
            if(question.isOr0 && this.Score!=question.Mark)
                this.Score = 0;

        }
        public  void refresh2()
        {
            this.Score = calcScore((question as QuestionOptinalMulti).questionOptions.OrderBy(x => x.correctColomn).Select(x => x.id).ToList(), columnsIndex, byOrder: false, OneWongZero: question.isOr0);
        }
        public override string clacl()
        {
            if (question is TabledChoosed tablc)
            {
                var questionOptions = tablc.questionOptions;//.Where(x=> x.QuestionId==QuestionId).ToList();
                var a = new HashSet<string>[tablc.row.Count];
                for (var z = 0; z < a.Count(); ++z)
                    a[z] = new HashSet<string>();
                
                string Answer = "";
                if (tablc.viewType == QuestionOptinalMulti.ViewType.DragAndDrop)
                {
                    for (int i = 1; i < tablc.row.Count; ++i) {
                        var z= columnsIndex.Select((value, index) => new { value, index }).Where(x => x.value == i).Select(x => questionOptions[x.index].title.ToString());
                        if (z.Count() > 0)
                            Answer += $"[{z.Aggregate((l, r) => $"{l},{r}")}]";
                        else
                            Answer += "[]";
                    }
                }
                else
                {
                    for (var z = 0; z < columnsIndex.Count; ++z)
                        Answer += $"{(char)('A' + columnsIndex[z] - 1)}";
                }
                this.Content = Answer;
                return Answer;
            }
            {
                var questionOptions = (question as QuestionOptinal).questionOptions;//.Where(x=> x.QuestionId==QuestionId).ToList();
                var a = new HashSet<string>[(question as QuestionOptinal).row.Count];
                for (var z = 0; z < a.Count(); ++z)
                    a[z] = new HashSet<string>();
                


                for (var z = 0; z < columnsIndex.Count; ++z)
                    if (columnsIndex[z]!=0)
                        a[columnsIndex[z]].Add(questionOptions[z].title.ToString());
                var Answer = a.Select(x => x != null && x.Count > 0 ? x.Aggregate((l, r) => $"{l},{r}") : "").Aggregate((l, r) => $"{l}|{r}");
                this.Content = Answer;
                return Answer;
            }
        }


    }
    public class QuestionOptinalOrderedResponse : QuestionOptinalResponse
    {

        public override string clacl()
        {

            {
                var questionOptinal = (question as QuestionOptinal);
                if (questionOptinal == null)
                    return question.correctAnswer ;
                var questionOptions = (questionOptinal).questionOptions;//.Where(x=> x.QuestionId==QuestionId).ToList();
                var a = new HashSet<string>[(question as QuestionOptinal).row.Count+1];
                for (var z = 0; z < a.Count(); ++z)
                    a[z] = new HashSet<string>();
                var CorrectAnswer = questionOptions
                    .Where(x => x.correctColomn != 0)
                    .OrderBy(x => x.correctColomn)
                    .GroupBy(x => x.correctColomn).Select(
                        x => x.Select(y => y.title.ToString()).Aggregate((l, r) => $"{l},{r}")
                    ).Aggregate((l, r) => $"{l}|{r}");


                for (var z = 0; z < columnsIndex.Count; ++z)
                    if (columnsIndex[z]+1 > 0)
                        a[columnsIndex[z]+1].Add(questionOptions[z].title.ToString());
                var Answer = a.Select(x => x != null && x.Count > 0 ? x.Aggregate((l, r) => $"{l},{r}") : "").Aggregate((l, r) => $"{l}|{r}");
                this.Content = Answer;
                return Answer;
            }
        }


    }


    public abstract class AHasTextResponse : Response
    {
        public string text { get; set; }
        public override string clacl()
        {
            this.Content = text;
            return text;
        }
    }
    public class SpeakingResponse : AHasTextResponse
    {
        [FileString]
        public string file { get; set; }
    }


    public class WritingResponse : AHasTextResponse
    {
        
        public override string clacl()
        {
            this.Content=text;
            return text;
        }
    }

    public class WordResponse : AHasTextResponse
    {


        public static bool CheckMyReg(string txt, string answer)
        {
            var answer2=answer;
            int i = 0;
            bool parntiz=false;
            
            foreach (var ch in txt)
            {
                if (ch == '(')
                {
                    parntiz=true;
                    continue;
                }
                if (ch == ')')
                {
                    parntiz=false;
                    continue;
                }
                //TODO
                if (answer2[i] != ch)
                    return false;
            }

            return true;
        }
        
        public override void refresh()
        {
            
            var trr = (question as WordQuestion).answerSheet;
            this.Score = (question as WordQuestion).getMark(text) ? question.Mark : 0;



        }
        public override string clacl()
        {
            this.Content = text;
            return text;
        }
       
    }



    public class ReviewViewModel
    {
        public Response response { get; set; }
        //public Question question { get; set; }
        public bool IsCorrectBool { get; set; }
        public ReviewViewModel()
        {

        }
        public ReviewViewModel(Question question, Response response)
        {
            this.response = response;
            //this.question = response.question;
            var answ = response.clacl();
            CorrectAnswer = question.correctAnswer;
            Answer = answ;

            


            CorrectAnswer = CorrectAnswer.Trim(',');
            Answer = Answer.Trim(',');

            QuestionMark = question.Mark;
            if (response.Score < QuestionMark)
                IsCorrectBool = false;

        }








        public string QuestionText { get; set; }

        public string CorrectAnswer { get; set; }

        public string Answer { get; set; }





        public decimal QuestionMark { get; set; }


    }
    
   
   
    public class QuantWhichIsGreaterResponse: Response{
        

        public ABGreaterType response { get; set; }
        public override string clacl()
        {
            
            {
                var questionOptinal = (question as QuantWhichIsGreaterQuestion);
                if (response == questionOptinal.abGreaterType)
                    this.Score = questionOptinal.Mark;
                else
                    this.Score = 0 ;
                this.Content = response switch
                {
                    ABGreaterType.aIsGreater => "A",
                    ABGreaterType.bIsGreater => "B",
                    ABGreaterType.equal => "C",
                    ABGreaterType.notKnown => "D",
                    _ =>   "_"
                };;
                return this.Content;
            }
        }
        public override void refresh()
        {

            clacl();



        }
    }
   
}
