// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EnglishToefl.Data.Repositories;
using ViewGeneratorBase;


namespace Models
{
    public partial class SelfDictionary : ASyncableEntity2, IUserSyncableEntity, IRemoveable
    {

        [Required]
        public string Word { get; set; }

        [Required]
        public string Description { get; set; }

        public Guid userId{ get; set; }

        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User.SelfDictionary))]
        public virtual User user { get; set; }

        public bool IsRemoved { get; set; }
    }
}