// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EnglishToefl.Data.Repositories;

namespace Models
{
    public partial class UserDetail
    {
        [NotMapped]
        public Guid id
        {
            get { return userId; }
        }

        [Display(Name ="نام کامل")]
        public string FullName { get{ return FirstName+" "+SurName;} }

        [Required]
        [MaxLength(200)]
        public string FirstName { get; set; }

        [Required]
        [MaxLength(200)]
        public string SurName { get; set; }

        [Key, Display(Name = "شناسه")]
        [MaxLength(450)]
        public Guid userId{ get; set; }

        [Required]
        [Range(0, 120)]
        public int RequiredMark { get; set; }

        [Required]
        public int MonthToExam { get; set; }

        //[Required]
        public string ProfileImageBase64 { get; set; }

        //[Required]
        public string Result { get; set; }

        //[Required]
        public string ResultDetail { get; set; }

        public int CityId { get; set; }


        [ForeignKey(nameof(CityId))]
        [InverseProperty(nameof(City.userDetail))]
        public virtual City city { get; set; }

        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User.UserDetail))]
        public virtual User user { get; set; }
    }
}